### PR TITLE
Add quic transport and ipv6

### PR DESCRIPTION
**Pull request by notassigned**

### CODE REVIEW

**Comment by alecbcs** [comment]
@notassigned what happens if another interface is already using the specified port for the libp2p instance? Before as long as the port was the default we'd automatically find an open port, but now it looks like the system will just fail unless the user manually configures each interface with a separate port?

P.S. Thanks for the PR and your interest in the project! And I apologize for the delay getting to this!

**Comment by notassigned** [comment]
> @notassigned what happens if another interface is already using the specified port for the libp2p instance? Before as long as the port was the default we'd automatically find an open port, but now it looks like the system will just fail unless the user manually configures each interface with a separate port?
> 
> P.S. Thanks for the PR and your interest in the project! And I apologize for the delay getting to this!

Yeah sorry, I forgot that I deleted that when I initially removed TCP. You're right that it would fail if the port couldn't be used. There are a number of ways that we could handle this, like having the user specify different UDP and TCP ports, or just having one port specified in the config and then selecting a random port if it is already taken for TCP|UDP on the machine.

Open to suggestions :)

**Comment by alecbcs** [comment]
@notassigned I think if the user types in a port different from the default (8001) then we should just try the port and then then know when/if it fails to bind. However, if the port is the default we should pick a random port and attempt to bind on that.

**Comment by alecbcs** [comment]
Do you need any help finishing up this PR? I'm happy to take a look at it/merge it once you've added back in the auto port finding system.

**Comment by notassigned** [comment]
Added the port check back in, but I think there may be a problem with QUIC where it closes a connection with no open streams, sometimes causing a peer to be dialed when a packet is written to the interface thus blocking other packets from going to other peers. I have a different branch which refactors the way the connections are handled and the packets are written to peers from the interface which resolves this.

https://github.com/notassigned/hyprspace/tree/reliability-connectivity-upgrade

**Comment by alecbcs** [comment]
Interesting! I actually quite like your rewrite. Have you done any testing/benchmarking to see how the added complexity of using go channels affects bandwidth throughput?

**Comment by notassigned** [comment]
I've yet to do a side by side comparison with the original version. I want to bench it with many active peers. I'm also debugging why connectivity stops after some time, probably need to republish the discovery string periodically. I want to add some sort of IPC so that we can e.g. get connected peers and communicate with the daemon from the CLI.

One thing that's bugging me is that the stream read function is non-blocking, so it's spinnning the loop constantly even when there's no data. I have to look into how to get around that, I'm still new to Go.

**Comment by alecbcs** [comment]
Gotcha. I'll go ahead and merge this PR for the time being and then we can work on fixing up that infinite loop for another PR.

**Pull request merged**
